# Generated by Django 5.1.1 on 2024-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
