# Generated by Django 5.1.1 on 2024-09-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
