# Generated by Django 5.1.1 on 2024-10-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='collected_symptoms',
        ),
    ]
